/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.es.oi.gui;

import br.edu.utfpr.es.oi.util.Util;

/**
 *
 * @author JoaoPaulo
 */
public class JDialogAluno extends javax.swing.JDialog {

    /**
     * Creates new form JDialogProfessor
     * @param parent
     * @param modal
     */
    public JDialogAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabelFoto = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButtonTempoLivre = new javax.swing.JButton();
        jButtonOrientador = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonReuniao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonReuniao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aluno");
        setMaximumSize(new java.awt.Dimension(550, 410));
        setMinimumSize(new java.awt.Dimension(550, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel2.setText("E-mail:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel3.setText("RA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel4.setText("Area de Interesse:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel5.setText("Departamento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setEnabled(false);
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 120, 25));

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 168, 25));

        jTextField3.setEditable(false);
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 168, 25));

        jTextField4.setEditable(false);
        jTextField4.setEnabled(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 168, 25));

        jTextField5.setEditable(false);
        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 168, 25));

        jLabelFoto.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/es/oi/icons/icon_student_48.png"))); // NOI18N
        jLabelFoto.setToolTipText("Selecionar Foto");
        jLabelFoto.setAlignmentX(0.5F);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabelFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 170, 25));

        jButtonTempoLivre.setFont(new java.awt.Font("Arial Black", 1, 12));
        jButtonTempoLivre.setText("+");
        jButtonTempoLivre.setToolTipText("Visualizar Professor");
        jButtonTempoLivre.setMaximumSize(new java.awt.Dimension(41, 25));
        jButtonTempoLivre.setMinimumSize(new java.awt.Dimension(41, 25));
        jButtonTempoLivre.setPreferredSize(new java.awt.Dimension(41, 25));
        jButtonTempoLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempoLivreActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTempoLivre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 41, 25));

        jButtonOrientador.setFont(new java.awt.Font("Arial Black", 1, 12)); 
        jButtonOrientador.setText("+");
        jButtonOrientador.setToolTipText("Solicitar Reunião");
        jButtonOrientador.setMaximumSize(new java.awt.Dimension(41, 25));
        jButtonOrientador.setMinimumSize(new java.awt.Dimension(41, 25));
        jButtonOrientador.setPreferredSize(new java.awt.Dimension(41, 25));
        jButtonOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrientadorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOrientador, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 41, 25));

        jLabel6.setText("Orientador:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel7.setText("Tempo Livre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel8.setText(" Reunião:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jButtonReuniao.setFont(new java.awt.Font("Arial Black", 1, 12)); 
        jButtonReuniao.setText("+");
        jButtonReuniao.setToolTipText("Visualizar Professor");
        jButtonReuniao.setMaximumSize(new java.awt.Dimension(41, 25));
        jButtonReuniao.setMinimumSize(new java.awt.Dimension(41, 25));
        jButtonReuniao.setPreferredSize(new java.awt.Dimension(41, 25));
        jButtonReuniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReuniaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReuniao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 41, 25));

        jButton2.setText("Editar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 550, 10));

        jButton1.setText("Salvar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 20));

        jLabel9.setText("Buscar Usuários:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jButtonReuniao1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonReuniao1.setText("+");
        jButtonReuniao1.setToolTipText("Visualizar Professor");
        jButtonReuniao1.setMaximumSize(new java.awt.Dimension(41, 25));
        jButtonReuniao1.setMinimumSize(new java.awt.Dimension(41, 25));
        jButtonReuniao1.setPreferredSize(new java.awt.Dimension(41, 25));
        jPanel1.add(jButtonReuniao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 41, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        setSize(new java.awt.Dimension(566, 448));
        setLocationRelativeTo(null);
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
       
    }

    private void jButtonTempoLivreActionPerformed(java.awt.event.ActionEvent evt) {
        Util.abrirJDialogCentralizado(new JDialogProfessor(null, true));
    }

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
       
    }

    private void jButtonOrientadorActionPerformed(java.awt.event.ActionEvent evt) {
       Util.abrirJDialogCentralizado(new JDialogReuniao( null, true));
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       
    }

    private void jButtonReuniaoActionPerformed(java.awt.event.ActionEvent evt) {
        Util.abrirJDialogCentralizado(new JDialogTempoLivre(null, true));
    }


     
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonOrientador;
    private javax.swing.JButton jButtonReuniao;
    private javax.swing.JButton jButtonReuniao1;
    private javax.swing.JButton jButtonTempoLivre;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    
}
